{"name": "Login shows an error message when trying with invalid credentials", "status": "passed", "parameters": [{"name": "username", "value": "'asd'"}, {"name": "password", "value": "'testwise'"}], "start": 1716489111445, "stop": 1716489115883, "uuid": "f8549b07-d343-4318-b485-d4d6ff92371b", "historyId": "a54cc321888a36961e44b96ea0ac4502", "testCaseId": "6485cd1aa206d185bd707f422a9a9238", "fullName": "tests.test_login#test_invalid_login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "epic", "value": "Web UI"}, {"name": "story", "value": "Invalid login"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Julian"}, {"name": "thread", "value": "4284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}