{"name": "Login shows an error message when trying with invalid credentials", "status": "passed", "parameters": [{"name": "username", "value": "'agileway'"}, {"name": "password", "value": "''"}], "start": 1716489097939, "stop": 1716489102404, "uuid": "d8b3a909-4a16-43aa-a3d4-682e84c896af", "historyId": "7e890931292c74659fd3fdb43cb00c1c", "testCaseId": "6485cd1aa206d185bd707f422a9a9238", "fullName": "tests.test_login#test_invalid_login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "epic", "value": "Web UI"}, {"name": "story", "value": "Invalid login"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Julian"}, {"name": "thread", "value": "4284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}