{"name": "Login shows an error message when trying with invalid credentials", "status": "passed", "parameters": [{"name": "username", "value": "''"}, {"name": "password", "value": "''"}], "start": 1716489084468, "stop": 1716489088738, "uuid": "c7b177b6-327d-4fe0-ae23-19b0cf394145", "historyId": "6485cd1aa206d185bd707f422a9a9238", "testCaseId": "6485cd1aa206d185bd707f422a9a9238", "fullName": "tests.test_login#test_invalid_login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "epic", "value": "Web UI"}, {"name": "story", "value": "Invalid login"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Julian"}, {"name": "thread", "value": "4284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}